pipeline {
    agent any
    triggers {
        pollSCM('* * * * *')
    }
    stages {

        stage("Compile") {
            steps {
                sh "./sistemaedu/gradlew compileJava"
            }
        }
        stage("Unit test") {
            steps {
                sh "./sistemaedu/gradlew test"
            }
        }
        stage("Code coverage") {
            steps {
        	    sh "./sistemaedu/gradlew jacocoTestReport"
        	 	publishHTML (target: [
         	        reportDir: 'build/reports/jacoco/test/html',
         			reportFiles: 'index.html',
         			reportName: 'JacocoReport'
         	    ])
         		sh "./sistemaedu/gradlew jacocoTestCoverageVerification"
         	}
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarQubePruebas') {
                    sh './sistemaedu/gradlew sonarqube'
                }
            }
        }
    }
}